language: erlang

notifications:
  email: false

otp_release:
  - 20.0
  - 19.3
  - 18.1
  - 17.4

script:
  - make
  - make test
  - make docs
  - make xref
  - if [ "$(erl -noshell -eval 'io:format(erlang:system_info(otp_release)), halt(0)')" -gt 18 ]; then make plt; make check; fi

